# Generated by Django 6.0.6 on 2026-07-01 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_tag', models.CharField(max_length=40)),
                ('relationship', models.CharField(choices=[('native', 'Native or first language'), ('heritage', 'Heritage language'), ('learned', 'Learned language'), ('other', 'Other relationship')], max_length=20)),
                ('proficiency', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('native_like', 'Native-like')], max_length=20)),
                ('other_language_name', models.CharField(blank=True, max_length=120)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='participants.participantprofile')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
                'constraints': [models.UniqueConstraint(fields=('profile', 'language_tag', 'relationship'), name='unique_profile_language_relationship')],
            },
        ),
    ]
