# Generated by Django 6.0.6 on 2026-08-16 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_add_participant_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantProfileSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('experiment_routing', 'Experiment routing'), ('practice_start', 'Practice start'), ('admin_created', 'Admin created')], max_length=40)),
                ('knows_mandarin', models.BooleanField(blank=True, null=True)),
                ('speaker_background', models.CharField(blank=True, max_length=20)),
                ('mandarin_level', models.CharField(blank=True, max_length=20)),
                ('languages', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_snapshots', to='participants.participant')),
            ],
            options={
                'ordering': ('-created_at', 'id'),
            },
        ),
    ]
