# Generated by Django 6.0.6 on 2026-08-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_participantprofilesnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantprofilesnapshot',
            name='source',
            field=models.CharField(choices=[('assessment_cycle_start', 'Assessment cycle start'), ('experiment_routing', 'Experiment routing'), ('practice_start', 'Practice start'), ('admin_created', 'Admin created')], max_length=40),
        ),
    ]
