# Generated by Django 6.0.6 on 2026-08-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0004_alter_participantprofilesnapshot_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='consent',
            name='share_recordings_on_huggingface',
            field=models.BooleanField(default=False),
        ),
    ]
