# Generated by Django 6.0.6 on 2026-07-12 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('source_text', models.TextField()),
                ('is_shared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_decks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PracticeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.TextField()),
                ('pinyin_text', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='practice.practicedeck')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='practice.practicedeck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-started_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PracticeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('server_elapsed_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='practice.practiceitem')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='practice.practicesession')),
            ],
            options={
                'ordering': ('started_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PracticeHintEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint_type', models.CharField(choices=[('character_pinyin', 'Character pinyin'), ('sentence_pinyin', 'Sentence pinyin')], max_length=30)),
                ('character', models.CharField(blank=True, max_length=10)),
                ('character_index', models.PositiveIntegerField(blank=True, null=True)),
                ('revealed_at', models.DateTimeField(auto_now_add=True)),
                ('revealed_at_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hint_events', to='practice.practiceattempt')),
            ],
            options={
                'ordering': ('revealed_at', 'id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('hint_type', 'sentence_pinyin')), fields=('attempt', 'hint_type'), name='unique_sentence_pinyin_hint_per_attempt'), models.UniqueConstraint(condition=models.Q(('hint_type', 'character_pinyin')), fields=('attempt', 'hint_type', 'character_index'), name='unique_character_pinyin_hint_per_attempt'), models.CheckConstraint(condition=models.Q(models.Q(('character', ''), ('character_index__isnull', True), ('hint_type', 'sentence_pinyin')), models.Q(('character__gt', ''), ('character_index__isnull', False), ('hint_type', 'character_pinyin')), _connector='OR'), name='practice_hint_fields_match_type')],
            },
        ),
        migrations.AddConstraint(
            model_name='practiceitem',
            constraint=models.UniqueConstraint(fields=('deck', 'sort_order'), name='unique_practice_item_sort_order'),
        ),
        migrations.AddConstraint(
            model_name='practiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('sort_order__gt', 0)), name='practice_item_sort_order_positive'),
        ),
    ]
