# Generated by Django 6.0.6 on 2026-08-10 20:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_add_practice_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='practicedeck',
            name='activity_type',
            field=models.CharField(default='reading_speaking', max_length=50),
        ),
        migrations.AddField(
            model_name='practicedeck',
            name='is_builtin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='practicedeck',
            name='response_type',
            field=models.CharField(default='audio', max_length=50),
        ),
        migrations.AddField(
            model_name='practicedeck',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, validators=[django.core.validators.RegexValidator(message='Use lowercase letters, numbers, and underscores.', regex='^$|^[a-z0-9_]+$')]),
        ),
        migrations.AddField(
            model_name='practicedeck',
            name='source_path',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='practicedeck',
            name='version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='practicedeck',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('slug', ''), _negated=True), ('version__isnull', False)), fields=('slug', 'version'), name='unique_practice_deck_slug_version'),
        ),
    ]
