# Generated by Django 6.0.6 on 2026-08-16 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_participantprofilesnapshot'),
        ('practice', '0002_practicedeck_activity_type_practicedeck_is_builtin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='profile_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='practice_sessions', to='participants.participantprofilesnapshot'),
        ),
    ]
