# Generated by Django 6.0.6 on 2026-08-29 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiments', '0005_assessmentcycle_and_more'),
        ('practice', '0003_practicesession_profile_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='assessment_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_sessions', to='experiments.assessmentcycle'),
        ),
    ]
