# Generated by Django 6.0.6 on 2026-06-13 05:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import mandarin_tone_recorder.recordings.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiments', '0003_basesyllable_stimulus_experimentstimulus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('finished', 'Finished'), ('aborted', 'Aborted')], default='active', max_length=20)),
                ('target_duration_seconds', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('target_reached_at', models.DateTimeField(blank=True, null=True)),
                ('continued_after_target', models.BooleanField(default=False)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('current_stimulus_index', models.PositiveIntegerField(blank=True, null=True)),
                ('current_stimulus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_in_sessions', to='experiments.stimulus')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recording_sessions', to='experiments.enrollment')),
            ],
        ),
        migrations.CreateModel(
            name='RecordingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('stimulus_index', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('attempt_number', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('timed_out', 'Timed out'), ('speaker_rejected', 'Speaker rejected'), ('aborted', 'Aborted'), ('save_failed', 'Save failed')], max_length=30)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('raw_audio', models.FileField(blank=True, max_length=500, upload_to=mandarin_tone_recorder.recordings.models.recording_upload_to)),
                ('wav_audio', models.FileField(blank=True, max_length=500, upload_to=mandarin_tone_recorder.recordings.models.recording_upload_to)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stimulus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recording_attempts', to='experiments.stimulus')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='recordings.recordingsession')),
            ],
            options={
                'ordering': ('session', 'stimulus_index', 'attempt_number'),
            },
        ),
        migrations.AddConstraint(
            model_name='recordingsession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('current_stimulus__isnull', True), ('current_stimulus_index__isnull', True)), models.Q(('current_stimulus__isnull', False), ('current_stimulus_index__isnull', False)), _connector='OR'), name='recording_current_stimulus_fields_match'),
        ),
        migrations.AddConstraint(
            model_name='recordingsession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ended_at__isnull', True), ('status', 'active')), models.Q(('ended_at__isnull', False), ('status__in', ('finished', 'aborted'))), _connector='OR'), name='recording_session_end_matches_status'),
        ),
        migrations.AddConstraint(
            model_name='recordingsession',
            constraint=models.CheckConstraint(condition=models.Q(('target_duration_seconds__gt', 0)), name='recording_session_target_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='recordingsession',
            constraint=models.CheckConstraint(condition=models.Q(('current_stimulus_index__isnull', True), ('current_stimulus_index__gt', 0), _connector='OR'), name='recording_current_stimulus_index_positive'),
        ),
        migrations.AddIndex(
            model_name='recordingattempt',
            index=models.Index(fields=['stimulus', 'status'], name='recordings__stimulu_4f725e_idx'),
        ),
        migrations.AddConstraint(
            model_name='recordingattempt',
            constraint=models.UniqueConstraint(fields=('session', 'stimulus_index', 'attempt_number'), name='unique_session_stimulus_attempt_number'),
        ),
        migrations.AddConstraint(
            model_name='recordingattempt',
            constraint=models.CheckConstraint(condition=models.Q(('duration_seconds__isnull', True), ('duration_seconds__gte', 0), _connector='OR'), name='recording_attempt_duration_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='recordingattempt',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_number__gt', 0), ('stimulus_index__gt', 0)), name='recording_attempt_numbers_positive'),
        ),
    ]
