# Generated by Django 6.0.6 on 2026-06-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiments', '0003_basesyllable_stimulus_experimentstimulus_and_more'),
        ('recordings', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recordingsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('enrollment',), name='unique_active_recording_session_per_enrollment'),
        ),
    ]
