# Generated by Django 6.0.6 on 2026-06-14 16:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0002_one_active_session_per_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordingattempt',
            name='recorded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
